### ISSUE TITLE
Removing the Rack::Lock middleware?

### ISSUE THREAD

**Issue by followfung** [websocket-rails/websocket-rails#119]
I'm not too familiar with rails and middleware, so I'm curious as to what Rack::Lock actually provides and why we need to remove it (as per Installation Instructions). My main confusion arises from only needing to remove it from the environments/development.rb and not production.

**Comment by akshayrawat** [comment]
Deleting Rack::Lock in development env fixes problems like [these](https://github.com/ngauthier/tubesock/issues/10#issuecomment-53841924). However it make cause problems like [this](https://github.com/ngauthier/tubesock/issues/10#issuecomment-70819550).

Still trying to figure out a correct approach or explanation for this.

**Comment by FooBarWidget** [comment]
@akshayrawat I don't think you should get rid of Rack::Lock just yet. I'm not saying Rack::Lock isn't problematic, but the issue goes deeper than that. See https://github.com/ngauthier/tubesock/issues/10#issuecomment-72539461
