### ISSUE TITLE
undefined method `connection' for nil:NilClass with rspec

### ISSUE THREAD

**Issue by ghost** [websocket-rails/websocket-rails#136]
I'm trying to test my controllers, but I can't figure out why rspec keeps vomiting on me when I try to run any tests.

The docs (updated 7 months ago) say to just add `require 'websocket_rails/spec_helpers'` to your `spec_helper` and you're good to go. That's not the case for me. I just get the following error when I try to run any test:

```
 Failure/Error: Unable to find matching line from backtrace
 NoMethodError:
   undefined method `connection' for nil:NilClass
```

The most recent few lines of the stack trace read:

```
# /Users/kyletcarlson/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/websocket-rails-2274438cc289/lib/websocket_rails/base_controller.rb:51:in `connection'
# /Users/kyletcarlson/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/websocket-rails-2274438cc289/lib/websocket_rails/base_controller.rb:160:in `delegate'
# /Users/kyletcarlson/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/websocket-rails-2274438cc289/lib/websocket_rails/base_controller.rb:164:in `method_missing'
# /Users/kyletcarlson/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/actionpack-4.0.0/lib/action_controller/test_case.rb:600:in `setup_controller_request_and_response'
# /Users/kyletcarlson/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/rspec-rails-2.14.0/lib/rspec/rails/adapters.rb:93:in `block (2 levels) in setup'
```

I tried requiring `websocket_rails/spec_helpers'` both inside and outside of my `RSpec.configure do |config|` block, but that didn't help either.

Can anyone please give me another suggestion about how to fix this?

**Comment by tlehman** [comment]
@kyletcarlson +5 magic internet karma for you, this solved my problem.
