### ISSUE TITLE
Can't use with passenger

### ISSUE THREAD

**Issue by luizcg** [websocket-rails/websocket-rails#14]
I'm using Ruby 1.9.2

I've just made a scaffold with two parameter title and body
followed the install instructions

Running with thin works.
Running with passenger gives the stack..

RuntimeError (eventmachine not initialized: evma_install_oneshot_timer):
  eventmachine (0.12.10) lib/eventmachine.rb:375:in `add_oneshot_timer'
  eventmachine (0.12.10) lib/eventmachine.rb:375:in`add_timer'
  eventmachine (0.12.10) lib/em/timers.rb:47:in `schedule'
  eventmachine (0.12.10) lib/em/timers.rb:35:in`initialize'
  websocket-rails (0.1.8) lib/websocket_rails/connection_adapters.rb:124:in `new'
  websocket-rails (0.1.8) lib/websocket_rails/connection_adapters.rb:124:in`start_ping_timer'
  websocket-rails (0.1.8) lib/websocket_rails/connection_adapters.rb:40:in `initialize'
  websocket-rails (0.1.8) lib/websocket_rails/connection_adapters/web_socket.rb:10:in`initialize'
  websocket-rails (0.1.8) lib/websocket_rails/connection_adapters.rb:14:in `new'
  websocket-rails (0.1.8) lib/websocket_rails/connection_adapters.rb:14:in`establish_connection'
  websocket-rails (0.1.8) lib/websocket_rails/connection_manager.rb:59:in `open_connection'
  websocket-rails (0.1.8) lib/websocket_rails/connection_manager.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:594:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in`call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.2) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `_run__607216680103759680__call__3159158661904658260__callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in`call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  railties (3.2.2) lib/rails/railtie/configurable.rb:30:in`method_missing'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/rack/application_spawner.rb:206:in`start_request_handler'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/utils.rb:479:in`safe_fork'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server.rb:180:in`start'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/spawn_manager.rb:253:in`block (2 levels) in spawn_rack_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/spawn_manager.rb:246:in`block in spawn_rack_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in`synchronize'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/spawn_manager.rb:244:in`spawn_rack_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  /Users/luiz/.passenger/standalone/3.0.12-x86_64-ruby1.9.2-macosx-10.6/support/helper-scripts/passenger-spawn-server:99:in `<main>'

  Rendered /Users/luiz/.rvm/gems/ruby-1.9.2-p290/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/_trace.erb (4.3ms)
  Rendered /Users/luiz/.rvm/gems/ruby-1.9.2-p290/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.4ms)
  Rendered /Users/luiz/.rvm/gems/ruby-1.9.2-p290/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (29.3ms)

**Comment by schnmudgal** [comment]
I think. Following should do the trick now.
[https://www.phusionpassenger.com/library/config/nginx/tuning_sse_and_websockets/](url)

And following for action cable
[https://www.phusionpassenger.com/library/config/nginx/action_cable_integration/](url)
