### ISSUE TITLE
Invalid HTTP format, parsing fails

### ISSUE THREAD

**Issue by avdept** [websocket-rails/websocket-rails#159]
I'm getting this strange exception in websocket_server log. Im using unicorn with nginx. Everything worked well on localhost, but doesnt on server.

Here is full stacktrace

<pre><code>Invalid request: Invalid HTTP format, parsing fails.
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/thin-1.6.1/lib/thin/request.rb:84:in `execute'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/thin-1.6.1/lib/thin/request.rb:84:in`parse'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/thin-1.6.1/lib/thin/connection.rb:41:in `receive_data'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/faye-websocket-0.7.0/lib/faye/adapters/thin.rb:44:in`receive_data'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:73:in `start'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/thin-1.6.1/lib/thin/server.rb:162:in`start'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/thin-1.6.1/lib/thin/controllers/controller.rb:87:in `start'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/websocket-rails-0.6.2/lib/rails/tasks/websocket_rails.tasks:13:in`block (3 levels) in <top (required)>'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/websocket-rails-0.6.2/lib/rails/tasks/websocket_rails.tasks:12:in `fork'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/websocket-rails-0.6.2/lib/rails/tasks/websocket_rails.tasks:12:in`block (2 levels) in <top (required)>'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:236:in`block in execute'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:231:in`execute'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
        /home/deploy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchronize'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:161:in`invoke'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in`block (2 levels) in top_level'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in`block in top_level'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:100:in`top_level'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/gems/rake-10.1.0/bin/rake:33:in`<top (required)>'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/bin/rake:23:in `load'
        /home/deploy/applications/feedbackhunter/shared/bundle/ruby/2.0.0/bin/rake:23:in`<main>'
</pre></code>

**Comment by dkonayuki** [comment]
Is there any solutions yet?
I have this issue even though my app protocol is http.

**Comment by bendangelo** [comment]
I solved it by running a flash policy server. https://github.com/futurechimp/flash_policy_server
