### ISSUE TITLE
Access one specific client from anywhere (regular controller / delayed task)

### ISSUE THREAD

**Issue by ccoenen** [websocket-rails/websocket-rails#164]
I am trying to send a message to one specific client, only. I have its client_id, but i can't figure out, how to use it to get to the connection. In an ideal world, this is what i'd like to write:

``` ruby
# Dream Code, not an actually working example (yet?)
class SomeController < ApplicationController # regular controller! Or console
  def poke #hypothetical action
    @device = Device.find(params[:id])
    client = WebsocketRails.clients[@device.client_id]
    # triggering?
    client.trigger "poke", {some: "properties"}
  end
end
```

The application is not really a "poke" but you get the idea. I found various tickets in here that suggested private channels. if there's a solution without channels, i'd prefert that. I am using channels for broadcasts already and i'd like to keep them seperate.

I was pry'ing around WebsocketRails.users - but that seems to be an empty hash in my case (my clients are not Users, and they are not authenticated). There seems to be no way to get into the ConnectionManager, at least none that i could find.

I would be thrilled if you could give me any pointers.

Ticket #104 is not really applying in this case, i am not trying to connect 2 clients to talk to each other, i'm just trying to push some information from the server to one specific client.

**Comment by umeshblader3** [comment]
How do i do use this in client side javascript
