### ISSUE TITLE
Resque crashes the app 

### ISSUE THREAD

**Issue by Rameshv** [websocket-rails/websocket-rails#183]
Hi,
  I am trying to use websocket-rails with my resque background jobs. But after installing websocket-rails, i cant initialize any resque queue or start resque-web.

whenever i call

```
Resque.enque MyQueue,Obj.id
```

 It fails with this error and crashes my rails app

```
FiberError - can't yield from root fiber
    /home/ramesh/.rvm/gems/ruby-2.0.0-p247/gems/redis-3.0.6/lib/redis/connection/synchrony.rb:81:in `yield'
    /home/ramesh/.rvm/gems/ruby-2.0.0-p247/gems/redis-3.0.6/lib/redis/connection/synchrony.rb:81:in `connect'
file: synchrony.rb location: yield line: 81
```

It only works after i remove websocket-rails completely from my app. i have tried 3 times to make sure that the issue is with websocket-rails. Can someone help me out

**Comment by ncri** [comment]
I have the same issue and tried using c.redis_options = {driver: :ruby}. Server starts up, but doesn't take any requests. (Re)loading a page in the browser does nothing. Just loads forever. No log output, as if the request doesnt even reach the server.

**Comment by zenkovnick** [comment]
the same issue like @ncri has
