### ISSUE TITLE
Can't establish connection to websocket from https domain

### ISSUE THREAD

**Issue by suprnova32** [websocket-rails/websocket-rails#189]
Hello,

first of all I love this gem, but I seem to have a problem that I cannot solve on my own. I want to use websockets for some functionality of my app and this app runs on a server on top of Passenger with https. My problem is that the websocket-rails JS client won't connect to the standalone server from the https domain. If I open the app on normal http everything works, but I need the https support. Can anyone help me?

Thanks!

**Comment by icanberk** [comment]
Hello, I have the same problem. I'm using apache in front of passenger. Can you let me know a little more about how I can get around this? Thank you!
