### ISSUE TITLE
Don't work with Rails 4.2.0.beta1

### ISSUE THREAD

**Issue by Samhane** [websocket-rails/websocket-rails#262]
Hi all, 
I have created a new rails application, added gem 'websocket-rails' in Gemfile, and when the server starts, I getting an error  in Chrome browser 
"WebSocket connection to 'ws://localhost:3000/websocket' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0 ".

In logfiles I found 
"Rack::Lint::LintError: Status must be >=100 seen as integer".

This error occurs because in module Rack, class Lint in method  _call(env)
in this line
status, headers, @body = @app.call(env)
status is -1.

You can reproduce the error using the application https://github.com/Samhane/test_websockets

**Comment by yihangho** [comment]
> +1, Problem still exists in anything above Rails 4.2.0.

@tyrauber, are you sure? I'm on Rails 4.2.0 stable and I'm not seeing this problem.

**Comment by Samhane** [comment]
I just updated to 4.2.0 stable, and all working correctly
