### ISSUE TITLE
Channel.trigger can send ANY data to subscribers without checking

### ISSUE THREAD

**Issue by ikasoumen** [websocket-rails/websocket-rails#283]
Hi,

I want to broadcast messages including HTML tags, but there is a security problem cause of channel.trigger.
I try to send messages including script tags to all subscribers with browser console, and then they received this message without checking in the server side's controller.
So I wanna disable this function "channel.trigger". Do you have any good Idea?

Thank you for reading.

**Comment by Oxynum** [comment]
You now have access to the [filter_for_channels](https://github.com/websocket-rails/websocket-rails/wiki/Filtering-Channel-Events) method. Is it enough for what you want ?

**Comment by ikasoumen** [comment]
self close.
