### ISSUE TITLE
Redis + websocket-rails = boom :)

### ISSUE THREAD

**Issue by t0d0r** [websocket-rails/websocket-rails#29]
Hi, 

I'm trying to use redis gem from rails console, but when I'm call method from redis I got this error:

```
1.9.3-p286 :001 > Redis.new().hkeys :a
RuntimeError: eventmachine not initialized: evma_connect_to_server
    from /Users/t0d0r/.rvm/gems/ruby-1.9.3-p286/gems/eventmachine-1.0.0/lib/eventmachine.rb:664:in `connect_server'
    from /Users/t0d0r/.rvm/gems/ruby-1.9.3-p286/gems/eventmachine-1.0.0/lib/eventmachine.rb:664:in `bind_connect'
    from /Users/t0d0r/.rvm/gems/ruby-1.9.3-p286/gems/eventmachine-1.0.0/lib/eventmachine.rb:640:in `connect'
```

If I remove the websocket-rails from my Gemfile - all is OK?

I need help how to solve this problem.

Loading development environment (Rails 3.2.8)
- em-synchrony (1.0.2)
- eventmachine (>= 1.0.0.beta.1)
- websocket-rails (0.2.0)

**Comment by krtschmr** [comment]
i still have this bug in rails 3.2 with websocket 0.7.
first of all ``redis-obejcts 0.5.3`` will never be found, so i need to manually add it to gemfile.
then it will crush
``RuntimeError - eventmachine not initialized: evma_connect_to_server:``

**Comment by bearfact** [comment]
+1
gems/eventmachine-1.0.8/lib/eventmachine.rb:536:in `start_unix_server': no unix-domain acceptor (RuntimeError)

**Comment by bfosberry** [comment]
+1 halp!
