### ISSUE TITLE
Heroku Support: WebsocketRails as a Service

### ISSUE THREAD

**Issue by wahyd4** [websocket-rails/websocket-rails#30]
Hi DanKnox,
       I use weboscket-rails in my app and it run evey well in localhost,but it can't be run heroku.
      The connection  established ,but can't send or receive message.How can I solve this problem?
      My js code is 

  var dispatcher = new WebSocketRails('localhost:3000/websocket');

```
dispatcher.on_open = function(data) {
    console.log('Connection has been established: ');
    console.log(dispatcher)
}
$('.submit-mess').click(function(){
    if ($('#content').val().replace(/\s+/, "") == ""){
        return ;
    }
    params= {};
    params.content = $('#content').val();
    params.slug = $('#slug').val()
    dispatcher.trigger('new_message',params);


});

dispatcher.bind('new_message', function(content) {
    $('#content').val("");
    $('.message-list').prepend(content).show('slow');
});
```

**Comment by Ricardonacif** [comment]
Hey everyone,

@moaa helped me make it work on Heroku with a few callouts:

Use Puma as the webserver
Use the websocket-rails gem branch: 'threadsocket-rails-sync' 
On puma.rb, don't call ```preload_app!``` and add the following:
```
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads 1, threads_count
```

**Comment by Samhane** [comment]
Hi
This branch ( 'threadsocket-rails-sync') is stable?
