### ISSUE TITLE
standalone + unicorn + redistogo + heroku

### ISSUE THREAD

**Issue by dp6ai** [websocket-rails/websocket-rails#311]
Hi,

Can you tell me if this configuration is actually possible?
I've setup up as per the wiki for standalone mode:

#websocket_rails.rb
```
config.standalone = true
uri = URI.parse(ENV["REDISTOGO_URL"])
    config.redis_options = {
      host: uri.host,
      port: uri.port,
      user: uri.user,
      password: uri.password
    }
```
#gemfile 
```
gem 'unicorn'
gem 'websocket-rails'
```
#blah.html.erb
```
var host = location.origin.replace(/^http:\/\//, '');
var dispatcher = new WebSocketRails(host + '/websocket');
```

#console output
```
WebSocket connection to 'ws://my-app.herokuapp.com/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500
```

#rails log
```
RuntimeError (eventmachine not initialized: evma_install_oneshot_timer)
```

I can get it working with puma as a standalone without redis using these instructions
http://stackoverflow.com/questions/25657405/websockets-not-working-in-my-rails-app-when-i-run-on-unicorn-server-but-works-o
It also works in standalone mode with foreman, but I have failed with standalone mode and unicorn on heroku.  
Any help would be really appreciated

thanks

**Comment by moaa** [comment]
websocket-rails needs EventMachine(thin) to run, so that is why you're having issues trying to use puma or unicorn.

I've done a bit of work to remove EventMachine as a dependency, if you would like to try it, update your gemfile:
```ruby
gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'threadsocket-rails'
```

Closing this issue for now.  If you're still having problems, please open a new one.
