### ISSUE TITLE
Socket connection closes twice

### ISSUE THREAD

**Issue by joshleaves** [websocket-rails/websocket-rails#312]
One of my WebSocket connections manage to close twice.

# Context #
Since we had some synchronization issues, our clients are instructed to trigger a manual "ping" event every 30 seconds. In case of failure, the client will disconnect and reconnects. In case of success, the client will be informed on whether its connection is still visible from the server and, if visible, will keep on, if unreachable, disconnect and reconnect.

# TL;DR #
16:50:41 Connection opened event
16:51:01 Connection closed event
16:51:11 NO ping event is received by the server
16:51:41 Second connection closed event

# Related logs #
    I [2015-02-04 16:50:41.704] [ConnectionManager] Connection opened: #<Connection::a250b59b8e1573b8a0d9>
    I [2015-02-04 16:50:41.709] [Dispatcher] Started Event: client_connected
    I [2015-02-04 16:50:41.709] [Dispatcher] Name: client_connected
    I [2015-02-04 16:50:41.709] [Dispatcher] Data: {"connection_id"=>"a250b59b8e1573b8a0d9"}
    I [2015-02-04 16:50:41.709] [Dispatcher] Connection: #<Connection::a250b59b8e1573b8a0d9>
    I [2015-02-04 16:50:41.727] [Dispatcher] Event client_connected Finished in 0.018025068 seconds

    I [2015-02-04 16:51:01.830] [ConnectionManager] Connection closed: #<Connection::a250b59b8e1573b8a0d9>
    I [2015-02-04 16:51:01.830] [Dispatcher] Started Event: client_disconnected
    I [2015-02-04 16:51:01.830] [Dispatcher] Name: client_disconnected
    I [2015-02-04 16:51:01.830] [Dispatcher] Connection: #<Connection::a250b59b8e1573b8a0d9>
    I [2015-02-04 16:51:01.837] [Dispatcher] Event client_disconnected Finished in 0.006179731 seconds

    I [2015-02-04 16:51:41.814] [ConnectionManager] Connection closed: #<Connection::a250b59b8e1573b8a0d9>
    I [2015-02-04 16:51:41.814] [Dispatcher] Started Event: client_disconnected
    I [2015-02-04 16:51:41.815] [Dispatcher] Name: client_disconnected
    I [2015-02-04 16:51:41.815] [Dispatcher] Connection: #<Connection::a250b59b8e1573b8a0d9>
    I [2015-02-04 16:51:41.824] [Dispatcher] Event client_disconnected Finished in 0.009086498 seconds

**Comment by moaa** [comment]
This will be fixed in the next release.  If you need the fixes right now you can update your gemfile:

```ruby
gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes'
```

Closing this issue.  If you are still having problems, please open a new one.
