### ISSUE TITLE
Using websockets on heroku

### ISSUE THREAD

**Issue by SenninSensei** [websocket-rails/websocket-rails#318]
hello sorry i my issue is repet, i'm new on rails and i making a application with websockets it works good on local server but i dont know how can i use it on heroku

**Comment by dcurletti** [comment]
I would suggest trying something else- either a different websocket library or not heroku.  Getting websocket-rails to work with rails + heroku has been a nightmare in my experience.

**Comment by cindoum** [comment]
This is what i started thinking about! 

I wont move from heroku (or do you know of any other similar host that offer so much feature?).

Do you have any libs to share with me to handle websocket (rails + heroku)? Is using Faye without websocket could be easier? 

Thank you

**Comment by cindoum** [comment]
I am having the exact same issue. I did tried to make it work with the standalone mode ut without success! 

@dcurletti, do you have any suggestion on any different libs to handle websocket with rails (deployed to heroku)? Is using Faye directly would make things easier?

Thank you

**Comment by byelipk** [comment]
@SenninSensei 

Just came across this issue and thought you might want to take a look at a prototype app I made. The goal was just to try and wire up websocket-rails in an app hosted on Heroku. I've since pulled it down but it worked just fine. I used Thin as my webserver.

https://github.com/byelipk/websocket-rails-heroku

**Comment by Oxynum** [comment]
It actually works with thin

**Comment by higgins777** [comment]
@SenninSensei 

I cloned that repo and like most examples I've seen it worked perfect locally. I tried to deploy strait into a single dyno Heroku and can't get it to work. Are there some additional steps to configure it for the Heroku instance?

You can see what I mean by trying to add a post: http://ws-dpo.herokuapp.com

I'll keep working with it this evening to see if I can figure out what I'm doing wrong :).

Thanks for the example!

**Comment by higgins777** [comment]
@SenninSensei 

Trying out your example on a free dyno and in my Chrome console I'm getting...
failed: Error during WebSocket handshake: 'Sec-WebSocket-Accept' header is missing 

Any ideas? You can take a look at http://ws-dpo.herokuapp.com

**Comment by byelipk** [comment]
@higgins777 

I just had a look at your link and it seems like you fixed the issue. I was able to post from a firefox browser and see the new content appear in my chrome browser.

In my console it logged out `Connection has been established`. There were no errors.

**Comment by higgins777** [comment]
Whoa! Your right... Very strange I changed absolutely nothing since my post. I was using Chromium on an office network so I wonder if that had any influence.

Either way thanks again!
