### ISSUE TITLE
Ensuring automatic start-up of Standalone Server when deploy on Unicorn/Nginx env

### ISSUE THREAD

**Issue by syriuszp** [websocket-rails/websocket-rails#332]
Hi all,
it's not real issue. It's more about "How to question" about workflow I should apply. I need in prod. env. to run Thin as Standalone Server but how to ensure automatic start-up of this Thin Standalone Server. Should I create appropriate capistarno task to start "websocket_rails:start_server" and then ensure appropriate init.d script to start-up Standalone Server as a demon when hosting server boot ? Thank you in advance for your kind directions.

**Comment by moaa** [comment]
Yup... what you've explained here is exactly how I would handle it.  Starting the standalone server should be just like any other rake task out there.  A quick google search returned quite a few results for init.d scripts and rake tasks.
