### ISSUE TITLE
Can't start websocketrails server in standalone mode. Any help?

### ISSUE THREAD

**Issue by truongduyng** [websocket-rails/websocket-rails#343]
When I ran "rake websocket_rails: start_server", it turned out "Websocket Rails Standalone Server listening on port 3001" in my terminal. 
But in my log file, it turned out errors: "Writing PID to /home/ntduy/workspace/sporta/tmp/pids/websocket_rails.pid
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3001, CTRL+C to stop
Invalid request: Invalid HTTP format, parsing fails....
Got 'Protocol error, got "H" as reply type byte' as initial reply byte. If you're in a forking environment, such as Unicorn, you need to connect to Redis after forking.  (Redis::ProtocolError)".
I did't see port 3001 for listening when I netstat

Any help? Thank you!

**Comment by deepsystm** [comment]
you need to install redis

**Comment by truongduyng** [comment]
how  to install it? by adding it to gemfile?

**Comment by deepsystm** [comment]
redis.io

**Comment by truongduyng** [comment]
ok. Thank you very much!
