### ISSUE TITLE
Websocket fails with two or more clients

### ISSUE THREAD

**Issue by epablo** [websocket-rails/websocket-rails#351]
Hi guys, I'm using websockets in a development app with Resque, when I run the app with two or more browsers (I mean, two websocket clients at the same time) I receive: Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)

Any ideas?, thanks in advance.

Websocket config:

config.standalone = true
config.synchronize = true
config.redis_options = {:host => 'localhost', :port => '6379'}

Gems:

rails (4.2.1)
redis (3.2.1)
websocket-rails (0.7.0)

Foreman:

redis: redis-server
resque: QUEUE=* rake environment resque:work
socket: rake websocket_rails:start_server

**Comment by nedoshel** [comment]
try to use hiredis redis driver for rescue:
Resque.configure do |config|
  config.redis = { 
    :host => 'localhost', 
    :port => 6379, 
    :driver => :hiredis
  }
end
something like that. it's helps for me with sidekiq

**Comment by epablo** [comment]
Hi, thanks for your response, I've moved from Resque to Sidekiq and everything is working great now.

I also changed the Websocket-rails gem to this:

gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes'


Thanks a lot!
