### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by rharriso** [websocket-rails/websocket-rails#385]
The open pull requests and issues are mounting, with no commit activity since June. Is this project dead?

**Comment by devmarwen** [comment]
I do think so, since the announcement of `action cable` integration to `rails`.

**Comment by mindaslab** [comment]
Is action cable the fork of this one?

**Comment by jstdoit** [comment]
action cable is only for rails 5.x+, but I wanna use it in my rails 4.1.x apps, is there any good advices?
