### ISSUE TITLE
Websocket-rails + Puma on production

### ISSUE THREAD

**Issue by JerryGreen** [websocket-rails/websocket-rails#389]
When I use Thin (in development environment) - everything works good.

When I use Puma (in production environment) - websocket server process doesn't run. In chrome console I get `Error during WebSocket handshake: Unexpected response code: 500`.

And also I don't see the process using `ps aux | grep websocket` (in development with Thin it's present).

What's wrong? Why the process doesn't run? Do I have to use standalone mode, redis and stuff like that or what?

UPD. [The answer](https://github.com/websocket-rails/websocket-rails/issues/389#issuecomment-173649777)

**Comment by rwu1997** [comment]
From https://github.com/websocket-rails/websocket-rails/issues/231 (user `moaa`'s comment on Oct 26, 2014) try doing 

```
gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'threadsocket-rails'
gem 'websocket-rails-js', github: 'websocket-rails/websocket-rails-js', branch: 'sub_protocols'
```

It worked for the most part for me on Puma, but I had some issues with the UserManager on standalone + synchronize. Let me know if you figure it out.

**Comment by JerryGreen** [comment]
@rwu1997 so do I have to use standalone mode or not? (and install redis, etc...)

**Comment by rwu1997** [comment]
I believe they took out eventmachine so it's not necessary. I'm still running into a `no variable or method 'sync'` error whether I use standalone/synchronization or not.

**Comment by JerryGreen** [comment]
@rwu1997 with your trick I run into `Error during WebSocket handshake: Unexpected response code: 500` in development environment too. Strange trick. I think I will use standalone mode. Looks like it's right way.

**Comment by rwu1997** [comment]
Did you use the two gems I listed? I'm still running into that nasty `no variable or method 'sync'` error.

**Comment by JerryGreen** [comment]
@rwu1997 yes. I don't use standalone (and synchronize). I don't use redis. I don't use User model or user manager or devise gem (I think I will include devise gem later). I did simple examples of subscribing and triggering. And it works!

Can't say anything about your problem. Did you listed `gem 'faye-websocket', '0.10.0'` in your Gemfile?

**Comment by rwu1997** [comment]
Yes I did. I'll need synchronize since websockets won't work across multiple instances. Thanks.
