### ISSUE TITLE
WebSocketRails is not defined

### ISSUE THREAD

**Issue by Candielope** [websocket-rails/websocket-rails#405]
Hi! I'm very new to this, so it's probably a silly mistake. I've tried two tutorials but I just cannot make it work. I get the same error message " Uncaught ReferenceError: WebSocketRails is not defined" in my inspector console and it's driving me mad, haha. Any idea what might be wrong? I have tried following both tutorials to the tea, but nothing seems to work. 

http://www.inspire.nl/blog/websockets-let-s-talk-about-real-time
http://hereisahand.com/using-websockets-in-a-rails-project/

Thank you!

**Comment by ghost** [comment]
I'm having the same issue, how did you solve it?
