### ISSUE TITLE
dispatcher in prod env

### ISSUE THREAD

**Issue by bl4d3** [websocket-rails/websocket-rails#74]
Hi,
I'm playing with websocket-rails in development env and it works fine. 
I have a question about dispatcher and prod env.
How should i modify this in prod?
var dispatcher = new WebSocketRails('localhost:3000/websocket'); 
as server address i tried my vps ip and localhost but i get an error in js console "unable to connect to ws://ip/websocket".
I'm under nginx and passenger module.

If i open http://myip/websocket i get this error:
eventmachine not initialized: evma_install_oneshot_timer

I noticed i have to run thin server so:
thin -e production -a myip start &
but when a client is connected i get this in thin log
!! Unexpected error while processing request: deadlock; recursive locking

Thank you

**Comment by atinder90** [comment]
Followed the steps but i still see this error in production.

RuntimeError (eventmachine not initialized: evma_install_oneshot_timer):

**Comment by de5pair** [comment]
I have the same error, running nginx with websockets standalone mode
